[metadata]
name = room_eye
version = 0.1.0
description = Smart room automation using computer vision on Raspberry Pi
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/Nautilus1011/room-eye
author = Jin Yasuda
author_email = ruitoby1011@gmail.com
license = AGPL-3.0-or-later
license_files =
    LICENSE
    NOTICE
classifiers =
    License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: Implementation :: CPython
    Programming Language :: Python :: Implementation :: PyPy

[options]
packages = find:
package_dir =
    = src
install_requires =
    numpy
python_requires = >=3.9

[options.packages.find]
where = src
exclude =
    tests*
    testing*

[options.extras_require]
dev =
    black
    covdefaults>=2.2
    coverage
    flake8
    isort
    pre-commit
    pytest
    pytest-env
    pyupgrade
    pyyaml
    tox
